apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod
spec:
  containers:
   - name: dummy-pod
     image: nginx
     volumeMounts:
       - mountPath: /var/lib/snap
         name: snapshot-1
  volumes:
   - name: snapshot-1
