apiVersion: v1
kind: Pod
metadata:
  name: pod-view
spec:
  containers:
   - name: pod-view
     image: nginx
     volumeMounts:
       - mountPath: /var/lib/mounted
         name: mounted
  volumes:
   - name: mounted
     hostPath:
       path: /
       type: Directory
