apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
   - name: pod-1
     image: nginx
     volumeMounts:
       - mountPath: /var/lib/pvc
         name: pvc
  volumes:
   - name: pvc
     persistentVolumeClaim:
       claimName: pvc
       readOnly: false
